sequenceDiagram
    participant IMS
    participant Databricks
    participant Segmentation
    participant GitHub
    participant Snowflake
    participant Streamlit

    IMS->>Databricks: Grab all IMS prod premiums and claims data.
    Databricks->>Databricks: Triggers a Job Run

    Databricks->>Segmentation: Pre-Processing
    Note right of Segmentation: Filter to correct business segments. \n Drop invalid records, adjust outlier records. \n Aggregate and merge.

    Databricks->>Segmentation: Enhancing Data
    Note right of Segmentation: Identify key information in new columns. \n Create new feature columns for segmentation. \n Generate transformations (grouping, percentiles, etc.).

    Databricks->>Databricks: Job Logging

    Databricks->>Segmentation: Actuarial Processing
    Note right of Segmentation: Calculate on-level premium. \n Trend losses. \n Develop losses.

    Databricks->>Databricks: Job Logging

    Databricks->>Segmentation: Insight Generation
    Note right of Segmentation: Remove duplicate/redundant segments. \n Exclude non-credible segments. \n Identify impactful segments (good & bad).

    Databricks->>Databricks: Job Logging

    Databricks->>Snowflake: Append-Only Data Storage
    Note right of Snowflake: Outputs from Databricks Job run are appended to Snowflake tables.

    Databricks->>GitHub: Regression Testing
    GitHub->>GitHub: Pull Request Conditions
    GitHub->>GitHub: Check Conditions Pass

    GitHub->>Streamlit: Update dashboard
    Streamlit->>Streamlit: End-User Dashboard
    Note right of Streamlit: Advanced Dashboard Logic.