sequenceDiagram
    participant Snowflake
    participant Databricks
    participant GitHub
    participant Streamlit

    Snowflake->>Databricks: Grab all raw, production premiums and claims data.
    Databricks->>Databricks: Triggers a Job Run

    Note right of Databricks: Filter to correct business segments. <br> Drop invalid records, adjust outlier records. <br> Aggregate and merge.

    Note right of Databricks: Identify key information in new columns. <br> Create new feature columns for segmentation. <br> Generate transformations (grouping, percentiles, etc.).

    Note right of Databricks: Calculate on-level premium. <br> Trend losses. <br> Develop losses.

    Note right of Databricks: Remove duplicate/redundant segments. <br> Exclude non-credible segments. <br> Identify impactful segments (good & bad).

    Databricks->>Databricks: Job Logging

    Databricks->>Snowflake: Append-Only Data Storage
    Note right of Snowflake: Outputs from Databricks Job run are appended to Snowflake tables.

    Databricks->>GitHub: Regression Testing
    GitHub->>GitHub: Pull Request Conditions
    GitHub->>GitHub: Check Conditions Pass

    GitHub->>Streamlit: Update Dashboard
    Snowflake->>Streamlit: Pull Latest Gold Layer Data
    Streamlit->>Streamlit: End-User Dashboard
    Note right of Streamlit: Advanced Dashboard Logic.